spring:
  application:
    name: CoffeeMachine

  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

  datasource:
    driver-class-name: org.postgresql.Driver
    username: makar
    password: 12345
    url: jdbc:postgresql://localhost:5432/coffee_machine
  jpa:
      database: postgresql
      show-sql: true

  flyway:
    user: makar
    password: 12345
    schemas: coffee_machine
    locations: filesystem:db/migration

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/v0/client/coffee
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-api-key')"
          bandwidths:
            - capacity: 30
              time: 1
              unit: hours

server:
    port: 8082
    error:
      include-message: always
      include-stacktrace: never

logging:
    level:
      org.hibernate.engine:
        transaction: debug

machine:
  api:
    version: 0
    cleaner:
        delay: 24
    statistic:
        clean-time: 5

swagger:
  api:
    version: 0.1
