
CREATE TABLE public.drinks (
   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
   "name" varchar(50) NOT NULL,
   CONSTRAINT drinks_pkey PRIMARY KEY (id),
   CONSTRAINT ukq1oglgivy66xcxjp43b1sbngx UNIQUE (name)
);

CREATE TABLE public.ingredients (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "name" varchar(50) NOT NULL,
    tank_remainder_ml int4 NOT NULL,
    CONSTRAINT ingredients_pkey PRIMARY KEY (id),
    CONSTRAINT ukj6tsl15xx76y4kv41yxr4uxab UNIQUE (name)
);

CREATE TABLE public.ratings (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    rating int8 NOT NULL,
    drink_id int8 NOT NULL,
    CONSTRAINT ratings_pkey PRIMARY KEY (id),
    CONSTRAINT uk6v47uejr1aq1q25yi3xb4h7jp UNIQUE (drink_id)
);
ALTER TABLE public.ratings ADD CONSTRAINT fkoawiyfjbahxpwrgew1gvimn3o FOREIGN KEY (drink_id) REFERENCES public.drinks(id);

CREATE TABLE public.receipts (
     percentage_ratio int4 NOT NULL,
     drink_id int8 NOT NULL,
     ingredient_id int8 NOT NULL,
     CONSTRAINT receipts_pkey PRIMARY KEY (drink_id, ingredient_id)
);

ALTER TABLE public.receipts ADD CONSTRAINT fkd4pnlptyg44e9fkyj8fhs4vxp FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);
ALTER TABLE public.receipts ADD CONSTRAINT fkm4x132w4a168290qroob9l04t FOREIGN KEY (drink_id) REFERENCES public.drinks(id);

CREATE TABLE public.rating_meta (
    id bigserial NOT NULL,
    clean_date timestamptz(6) NOT NULL,
    CONSTRAINT rating_meta_pkey PRIMARY KEY (id)
);